/**
 * Permission catalog — the single source of truth. The Permission table is
 * seeded FROM this constant; permission codes are never hand-typed elsewhere,
 * which prevents string drift between code and database.
 */
export interface PermissionDefinition {
  readonly code: string;
  readonly module: string;
  readonly description: string;
}

export const PERMISSION_CATALOG: readonly PermissionDefinition[] = [
  { code: 'tenant:read', module: 'core', description: 'View tenant details' },
  { code: 'tenant:manage', module: 'core', description: 'Create, update, suspend tenants' },
  { code: 'user:read', module: 'core', description: 'View users' },
  { code: 'user:manage', module: 'core', description: 'Create, update, deactivate users' },
  { code: 'role:read', module: 'core', description: 'View roles and their permissions' },
  { code: 'role:manage', module: 'core', description: 'Create roles, assign permissions and users' },
  { code: 'permission:read', module: 'core', description: 'View the permission catalog' },
  { code: 'location:read', module: 'core', description: 'View locations' },
  { code: 'location:manage', module: 'core', description: 'Create and update locations' },
  { code: 'module:read', module: 'core', description: 'View platform modules and tenant enablement' },
  { code: 'module:manage', module: 'core', description: 'Enable or disable modules for a tenant' },
  { code: 'audit:read', module: 'core', description: 'View audit logs' },
  { code: 'catalog:read', module: 'inventory', description: 'View product categories, brands, products, and barcodes' },
  { code: 'catalog:manage', module: 'inventory', description: 'Create, update, delete catalog entities' },
  { code: 'inventory:read', module: 'inventory', description: 'View stock levels and the inventory movement ledger' },
  { code: 'inventory:adjust', module: 'inventory', description: 'Perform manual stock adjustments' },
  { code: 'unit:read', module: 'devices', description: 'View autonomous retail units' },
  { code: 'unit:manage', module: 'devices', description: 'Create, update, delete retail units' },
  { code: 'device:read', module: 'devices', description: 'View devices' },
  { code: 'device:manage', module: 'devices', description: 'Create, update, delete devices' },
  { code: 'device:register', module: 'devices', description: 'Issue one-time edge registration tokens for devices' },
  { code: 'device:heartbeat', module: 'devices', description: 'Record device heartbeats' },
  { code: 'price-book:read', module: 'pricing', description: 'View price books, their versions, and the entries in each version' },
  { code: 'price-book:manage', module: 'pricing', description: 'Create price books and draft versions, set entries, activate a version, and roll back to an earlier one' },
  { code: 'price:read', module: 'pricing', description: 'Resolve the effective price of a product at a point in time' },
  { code: 'checkout:read', module: 'checkout', description: 'View checkout sessions and basket lines' },
  { code: 'checkout:manage', module: 'checkout', description: 'Create checkout sessions, mutate basket lines, and complete sessions into orders' },
  { code: 'order:read', module: 'checkout', description: 'View orders and order lines' },
  { code: 'order:manage', module: 'checkout', description: 'Cancel orders (no payment operations in Phase 5)' },
  { code: 'payment:read', module: 'payments', description: 'View payment intents, authorizations, captures, and events' },
  { code: 'payment:manage', module: 'payments', description: 'Create payment intents and manage their linkage (no live gateway)' },
  { code: 'payment:simulate', module: 'payments', description: 'Simulate provider-abstract authorization, capture, cancel/void, failure, and provider events' },
  { code: 'reconciliation:read', module: 'payments', description: 'View payment reconciliation records' },
  { code: 'payment:refund', module: 'payments', description: 'Refund money against a captured payment (bounded by what was captured; no live gateway)' },
  { code: 'reconciliation:manage', module: 'payments', description: 'Update reconciliation record status (mark reconciled/mismatch — no settlement accounting)' },
  { code: 'vision:read', module: 'cv', description: 'View vision events, SKU candidates, reviews, and evidence bundle lineage records' },
  { code: 'vision:ingest', module: 'cv', description: 'Ingest normalized product interaction events (with lineage-only evidence bundles) from vision adapters' },
  { code: 'vision:review', module: 'cv', description: 'Approve, reject, or manually override vision events, applying approved events to checkout baskets' },
  { code: 'inference:read', module: 'inference', description: 'View inference jobs, results, and SKU candidate rankings' },
  { code: 'inference:manage', module: 'inference', description: 'Create inference jobs and drive their lifecycle (start, fail)' },
  { code: 'inference:simulate', module: 'inference', description: 'Complete jobs with simulated adapter output (no real model execution)' },
  { code: 'inference:apply', module: 'inference', description: 'Convert a successful inference result into a Phase 7 vision event' },
  { code: 'video-asset:read', module: 'video-ingest', description: 'View video assets and their frame/crop artifacts' },
  { code: 'video-asset:manage', module: 'video-ingest', description: 'Upload controlled test videos and manage their metadata' },
  { code: 'video-asset:screen', module: 'video-ingest', description: 'Record the audited frame-content screening decision that releases (QUARANTINED to UPLOADED) or rejects (media removed) a quarantined upload' },
  { code: 'video-asset:process', module: 'video-ingest', description: 'Validate videos, extract frames/crops, and create inference jobs from crops' },
  { code: 'video-asset:delete', module: 'video-ingest', description: 'Delete video assets (removes the local file, keeps audited metadata)' },
  { code: 'store-flow:read', module: 'store-flow', description: 'View the autonomy policy and its versions, store-flow journeys, their projections, and the unified review queue' },
  { code: 'store-flow:manage', module: 'store-flow', description: 'Change the autonomy policy for a tenant or a store by publishing a new immutable policy version' },
  { code: 'store-flow:operate', module: 'store-flow', description: 'Issue and revoke store entry tokens, project observations onto baskets, and exit and settle a journey' },
  { code: 'store-flow:enter', module: 'store-flow', description: 'Redeem a store entry token, opening a shopper journey and its checkout session' },
  { code: 'store-flow:review', module: 'store-flow', description: 'Decide a queued observation once, recording the journey review and driving the matching vision event review' },
  { code: 'return:read', module: 'returns', description: 'View returns and cancellations, the stock they reversed, and the refunds they triggered' },
  { code: 'return:manage', module: 'returns', description: 'Record a return or cancel a settled order, reversing stock through the ledger and refunding the captured payment' },
  { code: 'cycle-count:read', module: 'returns', description: 'View cycle counts and stocktakes with their counted, projected, ledger and variance quantities' },
  { code: 'cycle-count:manage', module: 'returns', description: 'Open a count, record counted quantities, reconcile the count into ledger corrections, or abandon it' },
  { code: 'shrink:read', module: 'returns', description: 'View recorded shrink write-offs' },
  { code: 'shrink:record', module: 'returns', description: 'Write off a CV-detected loss as a SHRINK ledger movement' },
  { code: 'esl-gateway:read', module: 'esl', description: 'View electronic shelf label gateways and the vendor adapters this deployment offers' },
  { code: 'esl-gateway:manage', module: 'esl', description: 'Register, update, disable, and discover labels on ESL gateways' },
  { code: 'esl-label:read', module: 'esl', description: 'View electronic shelf labels, their bindings, and their battery/signal health' },
  { code: 'esl-label:manage', module: 'esl', description: 'Register labels, bind them to products and planogram cells, retire them, and request a re-render' },
  { code: 'esl-job:read', module: 'esl', description: 'View label update jobs, their attempts, and their failure reasons' },
  { code: 'esl-job:process', module: 'esl', description: 'Run a label update pass, reclaim expired worker leases, and reconcile labels against the price in force' },
  { code: 'loyalty-account:read', module: 'loyalty', description: 'View loyalty accounts and their derived points balances' },
  { code: 'loyalty-account:manage', module: 'loyalty', description: 'Enrol loyalty accounts, rename them, and suspend or close them' },
  { code: 'loyalty-points:read', module: 'loyalty', description: 'View the append-only points ledger of a loyalty account' },
  { code: 'loyalty-points:post', module: 'loyalty', description: 'Accrue and redeem points (idempotent; a redemption can never overdraw)' },
  { code: 'loyalty-points:adjust', module: 'loyalty', description: 'Append a manual adjustment, expiry, or reversal to a points ledger — the only way to correct a mistake, since movements are never edited or deleted' },
  { code: 'promotion:read', module: 'loyalty', description: 'View promotions, their versions and rules, and the explained price a shopper would be quoted' },
  { code: 'promotion:manage', module: 'loyalty', description: 'Create promotions and draft versions, set rules, and archive a promotion' },
  { code: 'promotion:activate', module: 'loyalty', description: 'Activate a promotion version and roll back to an earlier one — the moment a discount starts or stops applying to baskets' },
  { code: 'supplier:read', module: 'procurement', description: 'View suppliers and what each one charges for a product' },
  { code: 'supplier:manage', module: 'procurement', description: 'Create and update suppliers, archive them, and set supplier costs (every cost change appends a history row)' },
  { code: 'purchase-order:read', module: 'procurement', description: 'View purchase orders, their lines, and what has been received against each line' },
  { code: 'purchase-order:manage', module: 'procurement', description: 'Create draft purchase orders, submit them to a supplier, and cancel them' },
  { code: 'goods-receipt:read', module: 'procurement', description: 'View goods receipts and the inventory ledger movements each one produced' },
  { code: 'goods-receipt:manage', module: 'procurement', description: 'Record what physically arrived, admitting stock through the append-only inventory ledger' },
];
